spring:
  main:
    banner-mode: off
  application:
    name: rest-services-api

server:
  port: ${appPort:1443}
  error:
    include-stacktrace: always

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: "health,info"
  server:
    port: 8443


springdoc:
  swagger-ui:
    path: "/api-docs"
  api-docs:
    path: "/api-docs.json"

rest-service:
  name: "gcp-application-name"

logging:
  level:
    root: INFO
    uk.co.legacy.it.RestServicesApiApplication: INFO
    uk.co.legacy.it.api.resources: INFO
    uk.co.legacy.it.api.services: INFO



